### ISSUE TITLE
Auto-download no longer works

### ISSUE THREAD

**Issue by mincrmatt12** [ros-drivers/flir_camera_driver#18]
Pointgrey has merged their site with FLIR's, and as a result the `ptgrey.com` links no longer download properly, and instead all redirect to `flir.com`

**Comment by davidbsp** [comment]
Facing the same issue here. 
As a consequence, the compilation on melodic fails with error:

`
/home/user/catkin_ws/src/flir_camera_driver/spinnaker_camera_driver/include/spinnaker_camera_driver/set_property.h:29:10: fatal error: Spinnaker.h: No such file or directory
 #include "Spinnaker.h"
          ^~~~~~~~~~~~~
compilation terminated.
`

**Comment by davidbsp** [comment]
Hi! i was able to download the file from another source. 
You can find an updated "download_spinnaker" file at the end of this comment.

I have a new issue: I am trying to get this to work in Ubuntu 18.04 and ROS Melodic.

**a) Using the spinnaker-1.13.0.31 lib version, I get the following linking issues when compiling the pkg:**

```
/usr/bin/ld: warning: libswscale-ffmpeg.so.3, needed by //home/david/catkin_ws/build/flir_camera_driver/spinnaker_camera_driver/usr/lib/libspinvideoencoder.so.1, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libavcodec-ffmpeg.so.56, needed by //home/david/catkin_ws/build/flir_camera_driver/spinnaker_camera_driver/usr/lib/libspinvideoencoder.so.1, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libavutil-ffmpeg.so.54, needed by //home/david/catkin_ws/build/flir_camera_driver/spinnaker_camera_driver/usr/lib/libspinvideoencoder.so.1, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libavformat-ffmpeg.so.56, needed by //home/david/catkin_ws/build/flir_camera_driver/spinnaker_camera_driver/usr/lib/libspinvideoencoder.so.1, not found (try using -rpath or -rpath-link)
//home/david/catkin_ws/build/flir_camera_driver/spinnaker_camera_driver/usr/lib/libspinvideoencoder.so.1: undefined reference to `avformat_alloc_output_context2@LIBAVFORMAT_FFMPEG_56'
//home/david/catkin_ws/build/flir_camera_driver/spinnaker_camera_driver/usr/lib/libspinvideoencoder.so.1: undefined reference to `av_write_trailer@LIBAVFORMAT_FFMPEG_56'
//home/david/catkin_ws/build/flir_camera_driver/spinnaker_camera_driver/usr/lib/libspinvideoencoder.so.1: undefined reference to `avpicture_alloc@LIBAVCODEC_FFMPEG_56'
//home/david/catkin_ws/build/flir_camera_driver/spinnaker_camera_driver/usr/lib/libspinvideoencoder.so.1: undefined reference to `avcodec_open2@LIBAVCODEC_FFMPEG_56'
//home/david/catkin_ws/build/flir_camera_driver/spinnaker_camera_driver/usr/lib/libspinvideoencoder.so.1: undefined reference to `avformat_new_stream@LIBAVFORMAT_FFMPEG_56'
//home/david/catkin_ws/build/flir_camera_driver/spinnaker_camera_driver/usr/lib/libspinvideoencoder.so.1: undefined reference to `avcodec_flush_buffers@LIBAVCODEC_FFMPEG_56'
//home/david/catkin_ws/build/flir_camera_driver/spinnaker_camera_driver/usr/lib/libspinvideoencoder.so.1: undefined reference to `avcodec_encode_video2@LIBAVCODEC_FFMPEG_56'
//home/david/catkin_ws/build/flir_camera_driver/spinnaker_camera_driver/usr/lib/libspinvideoencoder.so.1: undefined reference to `avcodec_register_all@LIBAVCODEC_FFMPEG_56'
//home/david/catkin_ws/build/flir_camera_driver/spinnaker_camera_driver/usr/lib/libspinvideoencoder.so.1: undefined reference to `av_free@LIBAVUTIL_FFMPEG_54'
//home/david/catkin_ws/build/flir_camera_driver/spinnaker_camera_driver/usr/lib/libspinvideoencoder.so.1: undefined reference to `av_frame_alloc@LIBAVUTIL_FFMPEG_54'
//home/david/catkin_ws/build/flir_camera_driver/spinnaker_camera_driver/usr/lib/libspinvideoencoder.so.1: undefined reference to `av_rescale_q@LIBAVUTIL_FFMPEG_54'
//home/david/catkin_ws/build/flir_camera_driver/spinnaker_camera_driver/usr/lib/libspinvideoencoder.so.1: undefined reference to `avformat_write_header@LIBAVFORMAT_FFMPEG_56'
//home/david/catkin_ws/build/flir_camera_driver/spinnaker_camera_driver/usr/lib/libspinvideoencoder.so.1: undefined reference to `avformat_free_context@LIBAVFORMAT_FFMPEG_56'
//home/david/catkin_ws/build/flir_camera_driver/spinnaker_camera_driver/usr/lib/libspinvideoencoder.so.1: undefined reference to `sws_getContext@LIBSWSCALE_FFMPEG_3'
//home/david/catkin_ws/build/flir_camera_driver/spinnaker_camera_driver/usr/lib/libspinvideoencoder.so.1: undefined reference to `avio_open@LIBAVFORMAT_FFMPEG_56'
//home/david/catkin_ws/build/flir_camera_driver/spinnaker_camera_driver/usr/lib/libspinvideoencoder.so.1: undefined reference to `av_interleaved_write_frame@LIBAVFORMAT_FFMPEG_56'
//home/david/catkin_ws/build/flir_camera_driver/spinnaker_camera_driver/usr/lib/libspinvideoencoder.so.1: undefined reference to `avcodec_find_encoder@LIBAVCODEC_FFMPEG_56'
//home/david/catkin_ws/build/flir_camera_driver/spinnaker_camera_driver/usr/lib/libspinvideoencoder.so.1: undefined reference to `av_dump_format@LIBAVFORMAT_FFMPEG_56'
//home/david/catkin_ws/build/flir_camera_driver/spinnaker_camera_driver/usr/lib/libspinvideoencoder.so.1: undefined reference to `av_init_packet@LIBAVCODEC_FFMPEG_56'
//home/david/catkin_ws/build/flir_camera_driver/spinnaker_camera_driver/usr/lib/libspinvideoencoder.so.1: undefined reference to `avio_close@LIBAVFORMAT_FFMPEG_56'
//home/david/catkin_ws/build/flir_camera_driver/spinnaker_camera_driver/usr/lib/libspinvideoencoder.so.1: undefined reference to `av_register_all@LIBAVFORMAT_FFMPEG_56'
//home/david/catkin_ws/build/flir_camera_driver/spinnaker_camera_driver/usr/lib/libspinvideoencoder.so.1: undefined reference to `avcodec_close@LIBAVCODEC_FFMPEG_56'
//home/david/catkin_ws/build/flir_camera_driver/spinnaker_camera_driver/usr/lib/libspinvideoencoder.so.1: undefined reference to `sws_scale@LIBSWSCALE_FFMPEG_3'
collect2: error: ld returned 1 exit status
flir_camera_driver/spinnaker_camera_driver/CMakeFiles/spinnaker_test_node.dir/build.make:206: recipe for target '/home/david/catkin_ws/devel/lib/spinnaker_camera_driver/spinnaker_test_node' failed
make[2]: *** [/home/david/catkin_ws/devel/lib/spinnaker_camera_driver/spinnaker_test_node] Error 1
CMakeFiles/Makefile2:6635: recipe for target 'flir_camera_driver/spinnaker_camera_driver/CMakeFiles/spinnaker_test_node.dir/all' failed
make[1]: *** [flir_camera_driver/spinnaker_camera_driver/CMakeFiles/spinnaker_test_node.dir/all] Error 2
```


**b) Using a more recent version (spinnaker-1.18.0.17-amd64-pkg), I get the following error when compiling:** 

```
make[2]: *** No rule to make target 'flir_camera_driver/spinnaker_camera_driver/usr/lib/libSpinnaker.so', needed by '/home/david/catkin_ws/devel/lib/libSpinnakerCameraLib.so'.  Stop.
CMakeFiles/Makefile2:6712: recipe for target 'flir_camera_driver/spinnaker_camera_driver/CMakeFiles/SpinnakerCameraLib.dir/all' failed
```

**Updated "download_spinnaker" file:**

```
#!/usr/bin/env python
#
# Software License Agreement (BSD)
#
# @author    Mike Purvis <mpurvis@clearpathrobotics.com>
# @copyright (c) 2014, Clearpath Robotics, Inc., All rights reserved.
#
# Redistribution and use in source and binary forms, with or without modification, are permitted provided that
# the following conditions are met:
# * Redistributions of source code must retain the above copyright notice, this list of conditions and the
#   following disclaimer.
# * Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the
#   following disclaimer in the documentation and/or other materials provided with the distribution.
# * Neither the name of Clearpath Robotics nor the names of its contributors may be used to endorse or
#   promote products derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
# PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
# TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

import cookielib
import cStringIO
import logging
import shutil
import subprocess
import sys
import tarfile
import urllib
import urllib2
import os
import glob

logging.basicConfig(level=logging.INFO)

# changed by DP:
# LOGIN_URL = 'https://www.ptgrey.com/login'
# LOGIN_DATA = {
#     'Email': 'code@clearpathrobotics.com',
#     'Password': 'uNjRxoH6NMsJvi6hyPCH'
#     }

ARCHS = {
    'i386': (
        'http://intra.femtoeasy.eu/files/',
        'spinnaker-1.13.0.31-i386',
        'libSpinnaker.so.1.13.0.31'),
    'x86_64': (
        'http://intra.femtoeasy.eu/files/',
        'spinnaker-1.13.0.31-amd64',
        'libSpinnaker.so.1.13.0.31'),
    'armv7': (
        'http://intra.femtoeasy.eu/files/',
        'spinnaker-1.13.0.31-armhf',
        'libSpinnaker.so.1.13.0.31'),
    'armv8': (
        'http://intra.femtoeasy.eu/files/',
        'spinnaker-1.13.0.31-arm64',
        'libSpinnaker.so.1.13.0.31')
    }


archive_url, folder_name, shared_library = ARCHS[sys.argv[1]]
destination_folder = sys.argv[2]

# archive_url: http://intra.femtoeasy.eu/files/
# folder_name: spinnaker-1.13.0.31-amd64
# shared_library: libSpinnaker.so.1.13.0.31
# destination_folder: ~/catkin_ws/devel/lib/spinnaker_camera_driver/
# link online: http://intra.femtoeasy.eu/files/spinnaker-1.13.0.31-amd64-pkg.tar.gz

if not os.path.exists(os.path.join(os.getcwd(), "usr/lib/")):
    if not os.path.exists(os.path.join(os.getcwd(), folder_name)):

        #changed by DP: login is no longer necessary with the new download link:
        #logging.info("Logging into ptgrey.com.")
        cj = cookielib.CookieJar()
        opener = urllib2.build_opener(urllib2.HTTPCookieProcessor(cj))
        #opener.addheaders = [
        #     ('User-agent', 'Mozilla/5.0'),
        #     ('Referer', 'https://www.ptgrey.com')]
        #opener.open(LOGIN_URL, urllib.urlencode(LOGIN_DATA))

        logging.info("Downloading SDK archive.")
        resp = opener.open(archive_url+folder_name+"-pkg.tar.gz")  #changed by DP

        logging.info("Unpacking tarball.")
        with tarfile.open(mode="r:gz", fileobj=cStringIO.StringIO(resp.read())) as tar:
            tar.extractall(
)
    logging.info("Unpacking debs.")
    debs = glob.glob(os.path.join(os.getcwd(), folder_name, "libspinvideoencoder-*.deb"))
    debs += glob.glob(os.path.join(os.getcwd(), folder_name, "*spinnaker-*.deb"))
    for deb in debs:
        subprocess.call(['dpkg', '-x', deb, os.path.join(os.getcwd(), folder_name)])

    # Fix for 1.13.0.31
    os.remove(os.path.join(os.getcwd(), folder_name, "usr/lib/libspinnaker.so.1"))
    os.symlink(shared_library, os.path.join(os.getcwd(), folder_name, "usr/lib/libSpinnaker.so.1"))

    if not os.path.exists(os.path.join(os.getcwd(), "usr")):
        os.mkdir(os.path.join(os.getcwd(), "usr"))

    # For every folder/file, copy it into the /usr folder we just created.
    for filename in os.listdir(os.path.join(os.getcwd(), folder_name, "usr")):
        if not os.path.exists(os.path.join(os.getcwd(), "usr", filename)):
            shutil.move(os.path.join(os.getcwd(), folder_name, "usr", filename), os.path.join(os.getcwd(), "usr", filename))

    # now we do some thing for XML files; copy them next to the catkin binary
    xml_path = os.path.join(os.getcwd(), "usr/lib/")
    xml_files = os.listdir(xml_path)

    try:
        os.makedirs(destination_folder)
    except:
        logging.info("Error XML folder either exists or can't be created.")

    for files in xml_files:
        if files.endswith(".xml"):
            origin_file = os.path.join(xml_path, files)
            print('Copying ' + origin_file + ' to ' + destination_folder)
            shutil.copy(origin_file, destination_folder)

#-- libSpinnaker library: ~/catkin_ws/build/flir_camera_driver/spinnaker_camera_driver/usr/lib/libSpinnaker.so
#-- libSpinnaker include: ~/catkin_ws/build/flir_camera_driver/spinnaker_camera_driver/usr/include/spinnaker
```

I would love some feedback on this. Thanks!

**Comment by mincrmatt12** [comment]
Are you sure this doesn't violate the license? Unless that site has got express permission to redistribute the library it wouldn't be valid.

**Comment by mincrmatt12** [comment]
There appears to be an API for box, so we might be able to download it through that with a dummy box account.

**Comment by ghost** [comment]
@mincrmatt12 Have you looked at the box API any further is it a simple implementation?

**Comment by zlacelle** [comment]
I don't think we should be downloading the Spinnaker library automatically. Tightly coupling it is causing strange issues with newer versions of the Spinnaker library.

The SDK is available for free, and is easy enough to install. Decoupling this package from the underlying FLIR SDK will save pain down the road, I think.

**Comment by ghost** [comment]
Fixed in fec86c4

**Comment by rdesc** [comment]
Facing same issue `fatal error: Spinnaker.h: No such file or directory` it doesn't seem like the spinnaker sdk was properly downloaded. Trying to run with ROS melodic and Ubuntu 18.04.

**Comment by ghost** [comment]
@rdesc Can you provide more of the compilation output.  If its failing to download there should be signs before this stage.
